### ISSUE TITLE
Image profile crop example

### ISSUE THREAD

**Issue by johan-developer** [georg-jung/FaceAiSharp#24]
Hi Georg,

Your project it's really good. Congratz.

Do you have any example of cropping image for profile I saw your page but didn't see the code of this example.

Thank you,

Johan

**Comment by georg-jung** [comment]
Thanks for your positive words!
With the `FaceAiSharp.Bundle` package, cropping a profile picture works like this:

```csharp
using FaceAiSharp;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;

// adjust these lines to load your own image
using var hc = new HttpClient();
var groupPhoto = await hc.GetByteArrayAsync(
    "https://raw.githubusercontent.com/georg-jung/FaceAiSharp/master/examples/obama_family.jpg");
var img = Image.Load<Rgb24>(groupPhoto);

var det = FaceAiSharpBundleFactory.CreateFaceDetector();
FaceAiSharp.Applications.CropProfilePicture(det, img);
img.Save("obama_family_profilepic.jpg");
```

For more context see also this [StackOverflow answer](https://stackoverflow.com/a/77181111/1200847).

Additionally, you can always take a look at the [code of my tutorial project](https://github.com/georg-jung/explain-face-rec), in this case specifically here:
<https://github.com/georg-jung/explain-face-rec/blob/fe8a4e5d783b2a8eb22c33f8fcb9c8d3a89665eb/src/BlazorFace/Pages/Applications/ProfilePicture.razor#L54>

If you have any further questions, feel free to ask or otherwise close this issue.
