### ISSUE TITLE
Different Face Detection result compare to Demo Site

### ISSUE THREAD

**Issue by feliw** [georg-jung/FaceAiSharp#29]
Hi @georg-jung , first of all thanks for the great work that you put into this library.
Currently I was testing some pictures and lib is working great, but then I ran into 1 picture  where I cannot detect the face. I would clarify this picture as good picture, the face can be seen clearly only a mic blocking the mouth.

But funny thing is on your demo site part Face Recognition, the face was detected normally.

Can you suggest me where can I start to check, I already checkout your demo code make sure everything the same config and using the same lib version. But I'm using .NET6 MVC instead of Blazor .NET7.

Thanks before.

**Comment by georg-jung** [comment]
It'd be easier to help if I could take a look at your code and/or the specific image, can you create a GitHub repo with a repro?

One thing that comes to my mind is that it might help to reduce the resolution of the image before doing face detection. If you use a rather high-res image where the face fills a large part of the picture it might actually to big to be detected correctly (due to how these algorithms work). My demo/tutorial web app scales images down in many of the demos, which is why it might work there but not in your local experiments.

**Comment by feliw** [comment]
@georg-jung on point suggestion. After I resize it to smaller size the face is detected now.
Thanks.
